// client/src/components/usuario/login/Login.jsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import './Login.css';

const Login = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState(''); 

  const handleLogin = (e) => {
    e.preventDefault();
    // Aquí puedes agregar la lógica para manejar el inicio de sesión
    console.log('Iniciar sesión con:', email, password);
  };

  return (
    <section className='fondoLogin'>
      <div className="wrapper">
        <form onSubmit={handleLogin}>
          <h1>Login</h1>
          <div className="input-box">
            <input
              type="text"
              placeholder="Username"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
            <i className='bx bxs-user'></i>
          </div>
          <div className="input-box">
            <input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
            <i className='bx bxs-lock-alt'></i>
          </div>
          <div className="remember-forget">
            <label><input type="checkbox" /> Recuérdame</label>
            <Link to="/recuperarClave">Recuperar Contraseña</Link> {/* Usar Link para rutas de React Router */}
          </div>
          <button type="submit" className="btn">Login</button>
          <div className="register-link">
            <p>No tienes cuenta? <Link to="/register">Regístrate</Link></p> {/* Usar Link para rutas de React Router */}
          </div>
        </form>
      </div>
    </section>
  );
};

export default Login;

// frontend/hotel/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../service/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  email: string = '';
  password: string = '';
  
  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  onSubmit() {
    this.authService.login(this.email, this.password).subscribe({
      next: (response) => {
        const token = response.token;
        const idCliente = response.idCliente;
        const nombreCliente = response.nombre; 

        // Ahora se llama a storeToken con los 3 argumentos
        this.authService.storeToken(token, idCliente, nombreCliente);
        
        this.router.navigate(['/']);
      },
      error: (err) => {
        alert('Error en el inicio de sesión. Verifique sus credenciales.');
      },
      complete: () => {
        console.log('Autenticación completada.');
      }
    });
  }
}

<app-header></app-header>
<div class="container">
  <div class="left-section">
    <img src="/assets/familia.jpg" alt="Imagen de fondo" class="background-image">
  </div>
  <div class="right-section">
    <h1>Iniciar sesión</h1>

    <form (ngSubmit)="onSubmit()">
      <label for="login"></label>
      <input type="text" id="login" placeholder="Email" [(ngModel)]="email" name="email" required>
      
      <label for="password"></label>
      <input type="password" id="password" placeholder="Contraseña" [(ngModel)]="password" name="password" required>

      <div class="remember-forgot">
        <div>
          <input type="checkbox" id="remember-me">
          <label for="remember-me"> Recuérdame</label>
        </div>
        <a href="#">¿Olvidaste la contraseña?</a>
      </div>

      <button type="submit" class="sign-in-btn">Ingresar</button>
    </form>

    <div class="sign-up">
      <p>¿No tienes una cuenta? <a [routerLink]="['/registro']">Regístrate</a></p>
    </div>
  </div>
</div>
